version: '3.8'

services:
  app:
    build:
      context: docker
      dockerfile: ./php/Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: weather_alert
      MYSQL_USER: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-network

volumes:
  dbdata:
    driver: local

networks:
  laravel-network:
    driver: bridge